# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef590e568f5e7d202a56202abb4200aef06e8bcc6c2c1ef04a3b94f97e9837ea3e20dfca538a626f8795c1a243167ff940925d2e07a01409179bae9b1e1dcdb2

test:
  secret_key_base: 6bb6e9944385fa1c94fb709651d6daa696cc9a332c42d9892cba3ede642e89fd2b95f93352789dc649f315019aae21ba15d6b64f41e6fcb2c2d504ce6b30ce96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
